### ISSUE TITLE
Vertaisarviointi 2

### ISSUE THREAD

**Issue by shdewz** [jkuusto/rpg-random-encounters#2]
## Setting up

Setup instructions are very clear and concise; there were no issues with getting the project running.

## Usage

The app works as described and no issues were found with general usability. Editing the probability ranges does however not feel very intuitive.

## Technical

- Version control has no issues, and commit messages are very descriptive
- Database structure seems logical
- Python code mostly follows the given style guide and does not appear to have any major flaws
- JS code seems fine other than the mixed use of `var` and `let`, the former of which should ideally be avoided

Overall the app seems to be in a good state, mostly only lacking in the visual department.

**Comment by jkuusto** [comment]
Thank you for the feedback! All function-scoped variable assignments have now been changed to block-scoped assignments in the script file.

If you'd like to elaborate on how the probability range editing feature feels unintuitive, I might revamp the feature in a future update.

**Comment by shdewz** [comment]
> If you'd like to elaborate on how the probability range editing feature feels unintuitive, I might revamp the feature in a future update.

Editing one probability range seems to sometimes but not always change the range of the other type, and sometimes to a different range than specified. Might be a me issue as well, but it does feel a bit off.

**Comment by jkuusto** [comment]
Thanks. The entries are sorted by roll range value in descending order, so changing the value will reorder the entries in many cases. Perhaps this makes it look like the change affected the wrong entry because the entry isn't where you expect it to be anymore. Could this have been the issue?

**Comment by shdewz** [comment]
Yeah that clears it up a bit, probably fine to keep it that way then.

**Comment by jkuusto** [comment]
Alright, thanks. It would certainly be better if the user could rearrange the entries themself, but a feature like that is out of scope right now.
